#!/usr/bin/env python3
"""Generate CODE_INVENTORY.md from repository source files."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / "CODE_INVENTORY.md"

INCLUDE_PATHS = [
    ROOT / "vba",
    ROOT / "python",
    ROOT / "sql",
    ROOT / "scripts",
    ROOT / "tests",
    ROOT / ".github" / "workflows",
    ROOT / "Makefile",
]

ALLOWED_SUFFIXES = {".py", ".bas", ".sql", ".sh", ".yml", ".yaml", ".ps1", ".bat"}
ALLOWED_BASENAMES = {"Makefile"}


@dataclass
class Entry:
    path: Path
    language: str
    line_count: int
    summary: str


def language_for(path: Path) -> str:
    if path.name == "Makefile":
        return "Make"
    suffix = path.suffix.lower()
    return {
        ".py": "Python",
        ".bas": "VBA",
        ".sql": "SQL",
        ".sh": "Shell",
        ".yml": "YAML",
        ".yaml": "YAML",
        ".ps1": "PowerShell",
        ".bat": "Batch",
    }.get(suffix, "Text")


def first_meaningful_line(lines: list[str]) -> str:
    for raw in lines[:30]:
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#!"):
            continue
        if line.startswith("'" ):
            continue
        if line.startswith("REM "):
            continue
        if line.startswith("#"):
            # keep markdown headers or comments as fallback summary
            return line.lstrip("#").strip() or "(no summary found)"
        return line
    return "(no summary found)"


def iter_code_files() -> list[Path]:
    files: list[Path] = []
    for include in INCLUDE_PATHS:
        if include.is_file():
            files.append(include)
            continue
        if not include.exists():
            continue
        for path in include.rglob("*"):
            if not path.is_file():
                continue
            if path.name.startswith("."):
                continue
            if path.suffix.lower() in ALLOWED_SUFFIXES or path.name in ALLOWED_BASENAMES:
                files.append(path)
    return sorted(set(files), key=lambda p: str(p.relative_to(ROOT)).lower())


def build_entries() -> list[Entry]:
    entries: list[Entry] = []
    for path in iter_code_files():
        content = path.read_text(encoding="utf-8", errors="replace")
        lines = content.splitlines()
        entries.append(
            Entry(
                path=path,
                language=language_for(path),
                line_count=len(lines),
                summary=first_meaningful_line(lines),
            )
        )
    return entries


def generate_markdown(entries: list[Entry]) -> str:
    total_lines = sum(e.line_count for e in entries)
    lines = [
        "# Code Inventory",
        "",
        "> This file is auto-generated by `scripts/update_code_inventory.py`.",
        "> Run `python scripts/update_code_inventory.py` after code changes.",
        "",
        f"- Files indexed: **{len(entries)}**",
        f"- Total lines indexed: **{total_lines}**",
        "",
        "## Indexed Code Files",
        "",
        "| Path | Type | Lines | Summary |",
        "|---|---:|---:|---|",
    ]

    for entry in entries:
        rel = entry.path.relative_to(ROOT).as_posix()
        summary = entry.summary.replace("|", "\\|")
        lines.append(f"| `{rel}` | {entry.language} | {entry.line_count} | {summary} |")

    lines.extend(
        [
            "",
            "## Maintenance",
            "",
            "- Regenerate: `python scripts/update_code_inventory.py`",
            "- Verify in smoke checks: `bash scripts/run_stage_smoke.sh`",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> None:
    entries = build_entries()
    OUT_PATH.write_text(generate_markdown(entries), encoding="utf-8")
    print(f"Wrote: {OUT_PATH}")
    print(f"Files indexed: {len(entries)}")


if __name__ == "__main__":
    main()
